# -*- coding: utf-8 -*-
"""dz1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/157crtc4LXBtg2Tmlg1v1OES4abwXVT5g
"""

import numpy as np
import pandas as pd
from keras.datasets import boston_housing
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from google.colab import files

url = 'https://raw.githubusercontent.com/MatthewSulliv4n/keras1/master/TEST_CNN.csv'
url2 = 'https://raw.githubusercontent.com/MatthewSulliv4n/keras1/master/TRAIN_CNN.csv'
test = pd.read_csv(url)
train = pd.read_csv(url2)

dataset = test.astype('float32')
x_test = dataset.values[0:12,1:16]
y_test = dataset.values[0:12,0]

dataset2 = train.astype('float32')
x_train = dataset2.values[0:60,1:16]
y_train = dataset2.values[0:60,0]

mean = x_train.mean(axis=0)
std = x_train.std(axis=0)
x_train -= mean
x_train /= std

x_test -= mean
x_test /= std

model = Sequential()
model.add(Dense(40, activation='relu', input_shape=(x_train.shape[1],)))
model.add(Dense(120))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse', metrics=['mape'])

model.fit(x_train, y_train, epochs=10000, verbose=1)

mse, mae = model.evaluate(x_test, y_test, verbose=0)

pred = model.predict(x_test)

print("Средняя абсолютная ошибка:", mae)

print("Предсказано:", pred[1][0], ", правильно:", y_test[1])
print("Предсказано:", pred[10][0], ", правильно:", y_test[10])



